"""PDF export for Pre-Call Briefs.

Uses the same Markdown -> HTML -> WeasyPrint pipeline as call_note_export.py,
which is known to work reliably. Runs WeasyPrint in a thread pool executor
so it never blocks the async event loop.
"""

import asyncio
import logging
from datetime import datetime, timezone
from pathlib import Path

import markdown as md_lib
from weasyprint import HTML

from precall_store import get_precall_dir

logger = logging.getLogger(__name__)

_CALL_TYPE_LABELS = {
    "discovery": "Discovery",
    "followup": "Follow-Up",
    "technical_deep_dive": "Technical Deep Dive",
    "exec_briefing": "Exec Briefing",
    "poc_kickoff": "POC Kickoff",
    "poc_review": "POC Review",
    "champion_checkin": "Champion Check-In",
    "commercial": "Commercial",
}

# Identical to call_note_export — proven to work with WeasyPrint 68.1 on macOS.
_PDF_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<style>
@page {{
    size: letter;
    margin: 0.75in 0.85in 0.85in 0.85in;
    @bottom-center {{
        content: counter(page) " / " counter(pages);
        font-size: 9pt;
        color: #666;
        font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
    }}
    @bottom-right {{
        content: "SE Copilot -- Pre-Call Brief";
        font-size: 8pt;
        color: #999;
        font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
    }}
}}

* {{ box-sizing: border-box; }}

body {{
    font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
    font-size: 10.5pt;
    line-height: 1.6;
    color: #1a1a2e;
}}

.pdf-header {{
    border-bottom: 3px solid #632CA6;
    padding-bottom: 12pt;
    margin-bottom: 18pt;
}}
.pdf-header h1 {{
    font-size: 18pt;
    margin: 0 0 4pt 0;
    color: #632CA6;
}}
.pdf-header .meta {{
    font-size: 9pt;
    color: #555;
}}
.pdf-header .meta span {{
    margin-right: 18pt;
}}

.north-star {{
    background: #f0ebf8;
    border-left: 4pt solid #632CA6;
    padding: 10pt 14pt;
    margin-bottom: 16pt;
}}
.north-star .ns-label {{
    font-size: 8pt;
    font-weight: bold;
    text-transform: uppercase;
    letter-spacing: 0.06em;
    color: #632CA6;
    margin-bottom: 4pt;
}}
.north-star .ns-text {{
    font-size: 12pt;
    font-weight: bold;
    color: #1a1a2e;
    margin: 0;
}}

h2 {{
    font-size: 11pt;
    font-weight: bold;
    color: #632CA6;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    margin: 20pt 0 6pt;
    border-bottom: 1pt solid #e0d6f0;
    padding-bottom: 3pt;
    page-break-after: avoid;
}}

ul {{
    padding-left: 18pt;
    margin: 4pt 0;
}}
li {{
    font-size: 10pt;
    line-height: 1.5;
    margin-bottom: 3pt;
}}

p {{
    font-size: 10pt;
    line-height: 1.6;
    margin: 4pt 0;
}}

strong {{
    color: #1a1a2e;
}}

.objective {{
    font-size: 10pt;
    padding: 4pt 0;
    border-bottom: 1pt solid #f0f0f0;
}}

.question-block {{
    padding: 8pt 0;
    border-bottom: 1pt solid #e5e7eb;
    page-break-inside: avoid;
}}
.question-block:last-child {{
    border-bottom: none;
}}
.q-label {{
    font-size: 8pt;
    font-weight: bold;
    color: #632CA6;
    text-transform: uppercase;
    letter-spacing: 0.04em;
}}
.q-text {{
    font-size: 10pt;
    font-style: italic;
    font-weight: bold;
    margin: 2pt 0;
}}
.q-purpose {{
    font-size: 9pt;
    color: #6b7280;
}}
.q-followup {{
    font-size: 9pt;
    color: #9ca3af;
    margin-top: 2pt;
}}

.attendee-block {{
    padding: 6pt 0;
    border-bottom: 1pt solid #e5e7eb;
    page-break-inside: avoid;
}}
.attendee-name {{
    font-size: 10pt;
    font-weight: bold;
}}
.attendee-role {{
    font-size: 9pt;
    color: #6b7280;
    margin-left: 4pt;
}}
.attendee-line {{
    font-size: 9pt;
    color: #374151;
    margin: 2pt 0;
}}

.pdf-footer {{
    margin-top: 24pt;
    padding-top: 8pt;
    border-top: 1pt solid #e5e7eb;
    font-size: 8pt;
    color: #9ca3af;
    text-align: center;
}}
</style>
</head>
<body>

<div class="pdf-header">
    <h1>{title}</h1>
    <div class="meta">{meta_html}</div>
</div>

{body}

<div class="pdf-footer">Generated by SE Copilot &middot; {date_str}</div>

</body>
</html>
"""


def _esc(s: str) -> str:
    return (
        str(s or "")
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def brief_to_html(brief: dict) -> str:
    """Convert a PreCallBrief dict to a complete HTML document string."""
    company = _esc(brief.get("company_name", "Unknown"))
    call_type_key = brief.get("call_type", "")
    call_type_label = _esc(
        _CALL_TYPE_LABELS.get(call_type_key, call_type_key.replace("_", " ").title())
    )
    date_str = datetime.now(timezone.utc).strftime("%B %d, %Y")

    title = f"{call_type_label} Brief -- {company}"
    meta_html = (
        f"<span><strong>Company:</strong> {company}</span>"
        f"<span><strong>Call Type:</strong> {call_type_label}</span>"
        f"<span><strong>Generated:</strong> {date_str}</span>"
    )

    # Build body as HTML directly — no Markdown conversion needed since
    # we're constructing structured content, not converting prose.
    body_parts = []

    # North Star
    ns = _esc(brief.get("north_star", ""))
    if ns:
        body_parts.append(
            f'<div class="north-star">'
            f'<div class="ns-label">North Star -- What Makes This Call a Win</div>'
            f'<p class="ns-text">{ns}</p>'
            f'</div>'
        )

    # Where We Are
    situation = _esc(brief.get("situation_summary", ""))
    if situation:
        body_parts.append(f"<h2>Where We Are</h2><p>{situation}</p>")

    # What We Know / Don't Know — as two separate ul lists
    know = brief.get("what_we_know", [])
    dont = brief.get("what_we_dont_know", [])
    if know or dont:
        body_parts.append("<h2>Knowledge State</h2>")
        if know:
            body_parts.append(
                "<p><strong>What We Know</strong></p><ul>"
                + "".join(f"<li>{_esc(i)}</li>" for i in know)
                + "</ul>"
            )
        if dont:
            body_parts.append(
                "<p><strong>What We Don&rsquo;t Know</strong></p><ul>"
                + "".join(f"<li>{_esc(i)}</li>" for i in dont)
                + "</ul>"
            )

    # Objectives
    objectives = brief.get("call_objectives", [])
    if objectives:
        body_parts.append("<h2>Call Objectives</h2><ol>")
        for obj in objectives:
            body_parts.append(f"<li>{_esc(obj)}</li>")
        body_parts.append("</ol>")

    # Questions
    questions = brief.get("questions_to_ask", [])
    if questions:
        body_parts.append("<h2>Questions to Ask</h2>")
        for i, q in enumerate(questions, 1):
            followup_html = ""
            if q.get("follow_up_if"):
                followup_html = f'<p class="q-followup">If: {_esc(q["follow_up_if"])}</p>'
            body_parts.append(
                f'<div class="question-block">'
                f'<p class="q-label">Q{i}</p>'
                f'<p class="q-text">&ldquo;{_esc(q.get("question", ""))}&rdquo;</p>'
                f'<p class="q-purpose">Purpose: {_esc(q.get("strategic_purpose", ""))}</p>'
                f'{followup_html}'
                f'</div>'
            )

    # Attendee Prep
    attendees = brief.get("attendee_prep", [])
    if attendees:
        body_parts.append("<h2>Attendee Prep</h2>")
        for a in attendees:
            body_parts.append(
                f'<div class="attendee-block">'
                f'<p><span class="attendee-name">{_esc(a.get("name", ""))}</span>'
                f'<span class="attendee-role"> -- {_esc(a.get("inferred_role", ""))}</span></p>'
                f'<p class="attendee-line">Cares about: {_esc(a.get("what_they_care_about", ""))}</p>'
                f'<p class="attendee-line">How to engage: {_esc(a.get("how_to_engage", ""))}</p>'
                f'</div>'
            )

    # Proof Points
    proof = brief.get("key_proof_points", [])
    if proof:
        body_parts.append(
            "<h2>Key Proof Points</h2><ul>"
            + "".join(f"<li>{_esc(p)}</li>" for p in proof)
            + "</ul>"
        )

    # Things to Avoid
    avoid = brief.get("things_to_avoid", [])
    if avoid:
        body_parts.append(
            "<h2>Things to Avoid</h2><ul>"
            + "".join(f"<li>{_esc(a)}</li>" for a in avoid)
            + "</ul>"
        )

    body = "\n".join(body_parts)

    return _PDF_TEMPLATE.format(
        title=title,
        meta_html=meta_html,
        body=body,
        date_str=date_str,
    )


def _write_pdf_sync(html: str, out_path: Path) -> None:
    """Synchronous WeasyPrint call — must be run in an executor."""
    logger.info("WeasyPrint starting, html_len=%d, out=%s", len(html), out_path)
    try:
        HTML(string=html).write_pdf(str(out_path))
        logger.info("WeasyPrint completed: %s", out_path)
    except Exception as exc:
        logger.exception("WeasyPrint failed: %s", exc)
        raise


def generate_precall_pdf(record_id: str, brief: dict) -> Path:
    """Render a pre-call brief to PDF synchronously. Returns path to file."""
    out_dir = get_precall_dir()
    out_path = out_dir / f"{record_id}.pdf"
    html = brief_to_html(brief)
    _write_pdf_sync(html, out_path)
    logger.info("Generated pre-call brief PDF: %s", out_path)
    return out_path


async def generate_precall_pdf_async(record_id: str, brief: dict) -> Path:
    """Render a pre-call brief to PDF without blocking the event loop."""
    out_dir = get_precall_dir()
    out_path = out_dir / f"{record_id}.pdf"
    html = brief_to_html(brief)
    loop = asyncio.get_running_loop()
    await asyncio.wait_for(
        loop.run_in_executor(None, _write_pdf_sync, html, out_path),
        timeout=60.0,
    )
    logger.info("Generated pre-call brief PDF: %s", out_path)
    return out_path
